spring:
  application:
    name: garage-service
  datasource:
    url: jdbc:h2:mem:garage_service;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer:  org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  security:
    oauth2:
      resourceserver:
        jwt:
          # âœ… Utilise la variable d'environnement du docker-compose
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://keycloak:8080/realms/demo/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  port: 8080

garage:
  events:
    vehicle-created-topic:  VEHICLE_CREATED

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org. springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    com.renault.garage: INFO
    org.hibernate. SQL: DEBUG